### ISSUE TITLE
Optional: На блоке с видео выбрать самый интересный фрагмент матча и сделать его стартовой точке видео

### ISSUE THREAD

**Issue by rudnitskih** [RuchkoVlad/sports-app-landing#5]
Как это сделать написано здесь:
https://stackoverflow.com/a/5984558/4449154

**Comment by RuchkoVlad** [comment]
Дим почему-то не получилось по людски разделить коммиты, на уроке покажу что писало, коммитил по 2-3 issues

**Comment by rudnitskih** [comment]
окей, без проблем
